### ISSUE TITLE
命令行模式问题

### ISSUE THREAD

**Issue by Jerryzhao-z** [arcsecw/chinese_wubi#2]
刚刚用提供的测试文件跑了一下
`
git clone git@github.com:arcsecw/chinese_wubi.git
`
`
cd chinese_wubi
`
`
python w_trans.py --i chinese.txt --o wubi.txt --t 0
`

输出的wubi.txt文件是一个与chinese.txt相同的文件，没有能转换成五笔码
还请check一下是不是存在这个问题

**Comment by arcsecw** [comment]
没有这个问题啊
