### ISSUE TITLE
交互模式下跑给出的命令出现IOError

### ISSUE THREAD

**Issue by Jerryzhao-z** [arcsecw/chinese_wubi#3]
你好，我在python交互模式下跑了给出的代码

`from w_trans import W_trans`
`m_trans = W_trans()`
`outputfile = m_trans.chinese_wubi('chinese.txt', 'chinese_wubi.txt')`

得到的log是

> init /__chinese_wubi dict ...
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "w_trans.py", line 106, in chinese_wubi
>     self.__check_prepare(infile, type)
>   File "w_trans.py", line 36, in __check_prepare
>     self.__dict[type] = cPickle.load(open(type, 'r'))
> IOError: [Errno 2] No such file or directory: '/__chinese_wubi'

还请check一下

**Comment by Jerryzhao-z** [comment]
很有意思，交互模式下的sys.path[0]读到的地址和命令，文件中的不一样。
sys.path[0] 在交互模式下为空，并不指向module地址。可能换一种方式获取更好。

**Comment by arcsecw** [comment]
感谢你的反馈，抱歉回复的很晚了，我正在改进。

**Comment by arcsecw** [comment]
@Jerryzhao-z test new version ,thank u ^_^
