### ISSUE TITLE
有没有考虑过重码问题

### ISSUE THREAD

**Issue by chillyforest** [arcsecw/chinese_wubi#4]
“去云”“万尤”“鉴览”“竞兑”“芜芫”“苟茗”“茄茴”“ynky”“fpgc”……
例子很多，虽然对识别精确度的影响可能也不是很大。
不知道有没有考虑过把这些重码编上序号？

**Comment by arcsecw** [comment]
好的，感谢提醒

**Comment by arcsecw** [comment]
![image](https://user-images.githubusercontent.com/10559820/35711108-2b5ecad2-07f6-11e8-96cb-3e96031180dd.png)
有做处理，重码情况下，在后边随机加字母
